- hosts: localhost
  gather_facts: false

  tasks:
    - name: Welcome to ansible
      ansible.builtin.debug:
        msg: "Welcome to ansible {{ lookup('env', 'USER') }}"

    - name: Install apt packages
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      become: yes
      loop:
        - neovim
        - tmux
        - curl
        - fzf
        - exa
        - neofetch
        - ripgrep
        - htop
        - 'docker.io'
        - dos2unix
      tags:
        - base

    - name: Download and install .deb packages
      ansible.builtin.apt:
        deb: https://github.com/sharkdp/bat/releases/download/v0.18.1/bat_0.18.1_amd64.deb
      become: yes
      tags:
        - base

    - name: Add current user to docker group.
      user:
        name: "{{ lookup('env','USER') }}"
        groups: docker
        append: yes
      become: yes

    - name: Install packages from snap (classic)
      community.general.snap:
        name: alacritty
        classic: yes
      become: yes

    - name: Install packages from snap
      community.general.snap:
        name: procs
        classic: yes
      become: yes

    - name: Install Vim Plug (Plugin manager)
      ansible.builtin.shell: |
          curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim \
            --create-dirs \
            https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

    - name: Create fonts directory for installing fonts like Nerd fonts
      file:
        path: "$HOME/.local/share/fonts/nerdfonts"
        state: directory

    - name: Download fonts
      ansible.builtin.get_url:
        url: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/FiraCode.zip
        dest: /tmp/FiraCode.zip

    - name: Unzip downloaded font
      ansible.builtin.unarchive:
        src: /tmp/FiraCode.zip
        dest: "$HOME/.local/share/fonts/nerdfonts"

