- hosts: localhost
  gather_facts: false

  tasks:
    - name: Welcome to ansible
      ansible.builtin.debug:
        msg: Welcome to ansible

    - name: Install apt packages
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      become: yes
      loop:
        - neovim
        - tmux
        - curl
        - fzf

    - name: Install Vim Plug (Plugin manager)
      ansible.builtin.shell: |
          curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim \
            --create-dirs \
            https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
