- hosts: localhost
  gather_facts: false

  tasks:
    - name: Welcome to ansible
      ansible.builtin.debug:
        msg: Welcome to ansible

    - name: Install NeoVim
      ansible.builtin.apt:
        name: neovim
        state: present
      become: yes

    - name: Install tmux
      ansible.builtin.apt:
        name: tmux
        state: present
      become: yes

